# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='delta/ilist.proto',
  package='delta',
  serialized_pb='\n\x11\x64\x65lta/ilist.proto\x12\x05\x64\x65lta\"#\n\x0fiListEntryProto\x12\x10\n\x08iroot_id\x18\x01 \x02(\r\"3\n\niListProto\x12%\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x16.delta.iListEntryProto')




_ILISTENTRYPROTO = descriptor.Descriptor(
  name='iListEntryProto',
  full_name='delta.iListEntryProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='iroot_id', full_name='delta.iListEntryProto.iroot_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=63,
)


_ILISTPROTO = descriptor.Descriptor(
  name='iListProto',
  full_name='delta.iListProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entry', full_name='delta.iListProto.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=116,
)

_ILISTPROTO.fields_by_name['entry'].message_type = _ILISTENTRYPROTO
DESCRIPTOR.message_types_by_name['iListEntryProto'] = _ILISTENTRYPROTO
DESCRIPTOR.message_types_by_name['iListProto'] = _ILISTPROTO

class iListEntryProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ILISTENTRYPROTO
  
  # @@protoc_insertion_point(class_scope:delta.iListEntryProto)

class iListProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ILISTPROTO
  
  # @@protoc_insertion_point(class_scope:delta.iListProto)

# @@protoc_insertion_point(module_scope)
