// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: delta/ilist.proto

#ifndef PROTOBUF_delta_2filist_2eproto__INCLUDED
#define PROTOBUF_delta_2filist_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace delta {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_delta_2filist_2eproto();
void protobuf_AssignDesc_delta_2filist_2eproto();
void protobuf_ShutdownFile_delta_2filist_2eproto();

class iListEntryProto;
class iListProto;

// ===================================================================

class iListEntryProto : public ::google::protobuf::Message {
 public:
  iListEntryProto();
  virtual ~iListEntryProto();
  
  iListEntryProto(const iListEntryProto& from);
  
  inline iListEntryProto& operator=(const iListEntryProto& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const iListEntryProto& default_instance();
  
  void Swap(iListEntryProto* other);
  
  // implements Message ----------------------------------------------
  
  iListEntryProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const iListEntryProto& from);
  void MergeFrom(const iListEntryProto& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 iroot_id = 1;
  inline bool has_iroot_id() const;
  inline void clear_iroot_id();
  static const int kIrootIdFieldNumber = 1;
  inline ::google::protobuf::uint32 iroot_id() const;
  inline void set_iroot_id(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:delta.iListEntryProto)
 private:
  inline void set_has_iroot_id();
  inline void clear_has_iroot_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 iroot_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_delta_2filist_2eproto();
  friend void protobuf_AssignDesc_delta_2filist_2eproto();
  friend void protobuf_ShutdownFile_delta_2filist_2eproto();
  
  void InitAsDefaultInstance();
  static iListEntryProto* default_instance_;
};
// -------------------------------------------------------------------

class iListProto : public ::google::protobuf::Message {
 public:
  iListProto();
  virtual ~iListProto();
  
  iListProto(const iListProto& from);
  
  inline iListProto& operator=(const iListProto& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const iListProto& default_instance();
  
  void Swap(iListProto* other);
  
  // implements Message ----------------------------------------------
  
  iListProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const iListProto& from);
  void MergeFrom(const iListProto& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .delta.iListEntryProto entry = 1;
  inline int entry_size() const;
  inline void clear_entry();
  static const int kEntryFieldNumber = 1;
  inline const ::delta::iListEntryProto& entry(int index) const;
  inline ::delta::iListEntryProto* mutable_entry(int index);
  inline ::delta::iListEntryProto* add_entry();
  inline const ::google::protobuf::RepeatedPtrField< ::delta::iListEntryProto >&
      entry() const;
  inline ::google::protobuf::RepeatedPtrField< ::delta::iListEntryProto >*
      mutable_entry();
  
  // @@protoc_insertion_point(class_scope:delta.iListProto)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::delta::iListEntryProto > entry_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_delta_2filist_2eproto();
  friend void protobuf_AssignDesc_delta_2filist_2eproto();
  friend void protobuf_ShutdownFile_delta_2filist_2eproto();
  
  void InitAsDefaultInstance();
  static iListProto* default_instance_;
};
// ===================================================================


// ===================================================================

// iListEntryProto

// required uint32 iroot_id = 1;
inline bool iListEntryProto::has_iroot_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void iListEntryProto::set_has_iroot_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void iListEntryProto::clear_has_iroot_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void iListEntryProto::clear_iroot_id() {
  iroot_id_ = 0u;
  clear_has_iroot_id();
}
inline ::google::protobuf::uint32 iListEntryProto::iroot_id() const {
  return iroot_id_;
}
inline void iListEntryProto::set_iroot_id(::google::protobuf::uint32 value) {
  set_has_iroot_id();
  iroot_id_ = value;
}

// -------------------------------------------------------------------

// iListProto

// repeated .delta.iListEntryProto entry = 1;
inline int iListProto::entry_size() const {
  return entry_.size();
}
inline void iListProto::clear_entry() {
  entry_.Clear();
}
inline const ::delta::iListEntryProto& iListProto::entry(int index) const {
  return entry_.Get(index);
}
inline ::delta::iListEntryProto* iListProto::mutable_entry(int index) {
  return entry_.Mutable(index);
}
inline ::delta::iListEntryProto* iListProto::add_entry() {
  return entry_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::delta::iListEntryProto >&
iListProto::entry() const {
  return entry_;
}
inline ::google::protobuf::RepeatedPtrField< ::delta::iListEntryProto >*
iListProto::mutable_entry() {
  return &entry_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace delta

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_delta_2filist_2eproto__INCLUDED
