# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='core/static_info.proto',
  package='',
  serialized_pb='\n\x16\x63ore/static_info.proto\"A\n\x0e\x44\x65\x62ugInfoProto\x12\x11\n\tfile_name\x18\x01 \x02(\t\x12\x0c\n\x04line\x18\x02 \x02(\x05\x12\x0e\n\x06\x63olumn\x18\x03 \x02(\x05\"&\n\nImageProto\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x02(\t\"n\n\tInstProto\x12\n\n\x02id\x18\x01 \x02(\r\x12\x10\n\x08image_id\x18\x02 \x02(\r\x12\x0e\n\x06offset\x18\x03 \x02(\x04\x12\x0e\n\x06opcode\x18\x04 \x01(\r\x12#\n\ndebug_info\x18\x05 \x01(\x0b\x32\x0f.DebugInfoProto\"G\n\x0fStaticInfoProto\x12\x1a\n\x05image\x18\x01 \x03(\x0b\x32\x0b.ImageProto\x12\x18\n\x04inst\x18\x02 \x03(\x0b\x32\n.InstProto')




_DEBUGINFOPROTO = descriptor.Descriptor(
  name='DebugInfoProto',
  full_name='DebugInfoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='file_name', full_name='DebugInfoProto.file_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='line', full_name='DebugInfoProto.line', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='column', full_name='DebugInfoProto.column', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=91,
)


_IMAGEPROTO = descriptor.Descriptor(
  name='ImageProto',
  full_name='ImageProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='ImageProto.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='ImageProto.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=131,
)


_INSTPROTO = descriptor.Descriptor(
  name='InstProto',
  full_name='InstProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='InstProto.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='image_id', full_name='InstProto.image_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='InstProto.offset', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='opcode', full_name='InstProto.opcode', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='debug_info', full_name='InstProto.debug_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=133,
  serialized_end=243,
)


_STATICINFOPROTO = descriptor.Descriptor(
  name='StaticInfoProto',
  full_name='StaticInfoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='image', full_name='StaticInfoProto.image', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inst', full_name='StaticInfoProto.inst', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=245,
  serialized_end=316,
)

_INSTPROTO.fields_by_name['debug_info'].message_type = _DEBUGINFOPROTO
_STATICINFOPROTO.fields_by_name['image'].message_type = _IMAGEPROTO
_STATICINFOPROTO.fields_by_name['inst'].message_type = _INSTPROTO
DESCRIPTOR.message_types_by_name['DebugInfoProto'] = _DEBUGINFOPROTO
DESCRIPTOR.message_types_by_name['ImageProto'] = _IMAGEPROTO
DESCRIPTOR.message_types_by_name['InstProto'] = _INSTPROTO
DESCRIPTOR.message_types_by_name['StaticInfoProto'] = _STATICINFOPROTO

class DebugInfoProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEBUGINFOPROTO
  
  # @@protoc_insertion_point(class_scope:DebugInfoProto)

class ImageProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _IMAGEPROTO
  
  # @@protoc_insertion_point(class_scope:ImageProto)

class InstProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTPROTO
  
  # @@protoc_insertion_point(class_scope:InstProto)

class StaticInfoProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATICINFOPROTO
  
  # @@protoc_insertion_point(class_scope:StaticInfoProto)

# @@protoc_insertion_point(module_scope)
